name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.3.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "732e48f57199c5c53c712f041dd40915a5bd7a025a12b88cbeb5fe539f048216"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ""
