name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.3.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81e1305e00cf5e151f9b3091f7ad4b83575881717f862b4ee9b95a9a1fdde55b"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ""
