name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.3.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e966545de84248359e1d95236863c028dbbcfc7f7c253fa33f91261598a0c508"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ""
