name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.1.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89d2a9f2b5a3dbc8c29e686a3d5f6ffa32a3f97d292d62a085f5c719b926e3c4"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = "1.18.1 1.18"
