name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.2.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b32e8f801cafb4bc8a7b58275b819da863cd1a7a24157d929fcfab5e388356a9"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = "1.18.1 1.18"
