name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.2.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f93d1fa14cd55bf4af0cdd7a42862c803ef587947343f4fd011e9367def27fba"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = "1.18.1 1.18"
