name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.2.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "780b1171f7d140f6fb5dacb7d51210af7e276b5e344f1c31b9ec9e79f30bd8a2"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = "1.18.1 1.18"
