name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.3.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60082f1fe35b92e8528d5dcb004442564a59773cf92c4ed43e515ff054ecf390"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ""
