name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.3.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c11f58a8ca3951cf63b51f34a4bf38f58c39c8386cb39fb261f94bbaaa00791"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ""
