name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.3.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b898365b241445a57b5759bff028396373a04f0110ed9ab0c5f32335d6cfcd1e"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ""
