name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.3.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d00f20b249a59eeaea8ad3a292c72da9f440abfe9f0982320d48e6041ad872f1"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ""
