name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.2.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52bf74943c92248ab733df23cff3e16e46e97f2fede0f8280e2b59e350adc3ea"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = "1.18.1 1.18"
