name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.3.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fece45b854c7b39aee9a7fb0785dc638439a86e1c1dcc171d029ad797f85ada4"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ""
