name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.3.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4df2f6c293390972a02c4bd467c16cff56528c37cbc67e81b13ee198d965e3ac"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ""
