name = "Vanilla Compatible Pack"
author = "Small-Ku"
version = "0.5.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba98a6c50084caa8ad24e51d5c6d212179585269c6d0ce4629bcb937843e2b02"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = "1.21.10"
