name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.3.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d211719d77ea51b927f8e2f9020175dcf537af55ab2f226441c1688116633d8"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = "1.18.1 1.18"
