name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.3.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b50b85bb528795d31553fb139db04b40726bfc22765a6802c0eef67f8f744fcb"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ""
