name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.2.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfb9867159eb08cb66eae3458da23854fc45851e9b87627854c487376f6939e8"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = "1.18.1 1.18"
