name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.3.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6db636db832e0911d8aee2d7dcd78346d26ff96a2e3a5ef3124189325d6340ef"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ""
