name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.1.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46c1817562e16b278eb6e778ef7c70f50a28298b4a069c8695eb0f7f3e3029fe"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = "1.18.1 1.18"
