name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.3.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98076fec18a11151ccdd5592a82a76c8ef0740e32bd02385b7499cf7e86be7f2"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ""
