name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.3.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de2f4593ea30e415ecf0f6368bdef00d9907ba12ec0ee32fe74e8044a559047e"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ""
