name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.3.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c41cf7a37b4e64350fdcd1141c1547743ca678589330c5f8f8fefd6ea0c2b72"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ""
