name = "Vanilla Compatible 1.18"
author = "Small-Ku"
version = "0.3.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "255f45562eaaaf93fe21be340d00efc103e6f534674f2ab5dda9fcc20e0d8ef2"

[versions]
fabric = "0.14.12"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ""
