name = "1.17.1 for friends"
author = "Small-Ku"
version = "1.1.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "820e5fe60b49b7a19cf8ec3fec31d2c6001663052ded9bb6093daa3f983e57ae"

[versions]
fabric = "0.13.3"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
