name = "[Shader] Sildur's Vibrant shaders"
filename = "../shaderpacks/SildursVibrant.zip"
side = "client"

[download]
hash-format = "sha1"
hash = "98fba2189c28181cd2751fba4fc871bd5eba4878"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 4278029
project-id = 544096

[option]
optional = true
description = "A shaderpack revamps the lighting system and adds advanced effects while maintaining high performance and compatibility with many systems.\n改造光照系統、追加進階效果，並同時維持高效且相容於不同系統的光影包\nSee more at https://www.curseforge.com/minecraft/customization/sildurs-vibrant-shaders\n"
