name = "[Shader] Tea Shaders"
filename = "../shaderpacks/Tea.zip"
side = "client"

[download]
hash-format = "sha1"
hash = "c4a45a898f1fbebd46f1b007a91939c31bdf7865"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 4262597
project-id = 331780

[option]
optional = true
description = "A shaderpack add a little bit extra to vanilla Minecraft in a fully customizable way.\n以可設定的方式為原版增添視覺效果的光影包\nSee more at https://www.curseforge.com/minecraft/customization/beyondbelief-vanilla-reborn\n"
