name = "[Shader] Prismarine Shader"
filename = "../shaderpacks/Prismarine.zip"
side = "client"

[download]
url = "https://media.forgecdn.net/files/3786/80/Prismarine+V4.2a.zip"
hash-format = "sha1"
hash = "a4baf386249b4d316fece052ad4f5758037a2810"

[update]
[update.curseforge]
file-id = 3590068
project-id = 478295

[option]
default = false
optional = true
description = """
A BSL Shaders edit shaderpack aims to provide very nice and stunning visuals at low performance cost.
\u65e8\u5728\u9ad8\u6548\u63d0\u4f9b\u597d\u770b\u6548\u679c\u7684BSL\u884d\u751f\u5149\u5f71\u5305
See more at https://www.curseforge.com/minecraft/customization/prismarine-shader
"""
