name = "[Shader] Sildur's Enhanced Default"
filename = "../shaderpacks/SildursEnhancedDefault.zip"
side = "client"

[download]
hash-format = "sha1"
hash = "bba417d14a0a54165ffdb2cb21feac536af33816"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 4278034
project-id = 544140

[option]
optional = true
description = "A lightweight and highly customizable shaderpack maintains the vanilla look and adds shadows, reflections, TAA and even godrays.\n保持原版外觀並加入陰影、反射、TAA甚至聖光的輕量可自訂光影包\nSee more at https://www.curseforge.com/minecraft/customization/sildurs-enhanced-default\n"
