name = "[Shader] Sildur's Enhanced Default"
filename = "../shaderpacks/SildursEnhancedDefault.zip"
side = "client"

[download]
url = "https://media.forgecdn.net/files/3590/68/Sildur%27s+Enhanced+Default+v1.131+Fancy.zip"
hash-format = "sha1"
hash = "e5f3749689157216ea6adcbf6372e23f2de44f42"

[update]
[update.curseforge]
file-id = 3590068
project-id = 544140

[option]
default = false
optional = true
description = """
A lightweight and highly customizable shaderpack maintains the vanilla look and adds shadows, reflections, TAA and even godrays.
\u4fdd\u6301\u539f\u7248\u5916\u89c0\u4e26\u52a0\u5165\u9670\u5f71\u3001\u53cd\u5c04\u3001TAA\u751a\u81f3\u8056\u5149\u7684\u8f15\u91cf\u53ef\u81ea\u8a02\u5149\u5f71\u5305
See more at https://www.curseforge.com/minecraft/customization/sildurs-enhanced-default
"""
