name = "[Shader] Complementary Shaders"
filename = "../shaderpacks/Complementary.zip"
side = "client"

[download]
hash-format = "sha1"
hash = "f308b1fb3eea3557b4bab61ec4afec47d905f285"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 4279382
project-id = 385587

[option]
optional = true
description = "A shaderpack try to provide you with the most issueless experience possible.\n嘗試提供無瑕體驗的光影包\nSee more at https://www.curseforge.com/minecraft/customization/complementary-shaders\n"
