name = "[Shader] BSL Shaders"
filename = "../shaderpacks/BSL.zip"
side = "client"

[download]
hash-format = "sha1"
hash = "ddd94583683e3095ddc1db37f00752d9d92ec173"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 4119558
project-id = 322506

[option]
optional = true
description = "A shaderpack with high customization and optimization.\n可按需調整的高效光影包\nSee more at https://bitslablab.com/bslshaders/\n"
