name = "Animatica"
filename = "animatica-0.4+1.18.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/PRN43VSY/versions/0.4+1.18/animatica-0.4%2B1.18.jar"
hash-format = "sha1"
hash = "88814223cfa1aa19745529d852d545e5273f58d3"

[update]
[update.modrinth]
mod-id = "PRN43VSY"
version = "uoIGWJxI"

[option]
default = true
optional = true
description = """
Support the OptiFine animated texture format
\u652f\u6301 Optifine \u5f0f\u52d5\u614b\u6750\u8cea
"""
