name = "Animatica"
filename = "animatica-0.5+1.18.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/PRN43VSY/versions/0.5%2B1.18.2/animatica-0.5%2B1.18.2.jar"
hash-format = "sha1"
hash = "1073b1e722ea629ef72133cb9968156a0d8beeca"

[update]
[update.modrinth]
mod-id = "PRN43VSY"
version = "GYUKcduK"

[option]
optional = true
description = "Support the OptiFine animated texture format\n支持 Optifine 式動態材質\n"
default = true
