name = "AppleSkin"
filename = "appleskin-fabric-mc1.18.2-2.4.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/EsAfCjCV/versions/fabric-mc1.18.2-2.4.0/appleskin-fabric-mc1.18.2-2.4.0.jar"
hash-format = "sha1"
hash = "07cc0f6d00b184bef9c4390682c098d5ca52e67d"

[update]
[update.modrinth]
mod-id = "EsAfCjCV"
version = "gQRJj49P"

[option]
default = true
optional = true
description = """
Show information about food
\u986f\u793a\u98df\u7269\u8cc7\u8a0a
"""
