name = "Audaki Cart Engine: Faster Minecarts / Balanced for Survival / Vanilla Carts Improved"
filename = "audaki_cart_engine--fabric-mc1.18.2--v2.0.0.jar"
side = "server"

[download]
hash-format = "sha1"
hash = "2634396f999d637397b2b294d3cbdd419a7307c6"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 4006082
project-id = 520576
