name = "AutoReconnect"
filename = "autoreconnect-1.3.2.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3452/896/autoreconnect-1.3.2.jar"
hash-format = "murmur2"
hash = "3016890605"

[update]
[update.curseforge]
file-id = 3452896
project-id = 406211

[option]
default = false
optional = true
description = """
Auto reconnect to server
\u81ea\u52d5\u91cd\u65b0\u9023\u63a5\u4f3a\u670d\u5668
"""
