name = "AutoSwitch"
filename = "autoswitch-10.0.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/uSdcnlts/versions/rhoz92qn/autoswitch-10.0.0.jar"
hash-format = "sha512"
hash = "d692e78bf30fa22825e91f9e5a1cc99c11d7e6ec47d4c5402d792680d231fb5b2ad11f3e6315d40a93e557808d79c64d3866148ad5a9cc75eaaa3d76701c981b"

[update]
[update.modrinth]
mod-id = "uSdcnlts"
version = "rhoz92qn"

[option]
optional = true
description = "Auto switch tool\n自動切換工具\n"
