name = "Beenfo"
filename = "beenfo-1.18.2-fabric0.47.10-1.3.3.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/Bta0Pt47/versions/1.18.2-fabric0.47.10-1.3.3/beenfo-1.18.2-fabric0.47.10-1.3.3.jar"
hash-format = "sha1"
hash = "3aec8adb006bba66ca3570a512cde6e0f696c5a7"

[update]
[update.modrinth]
mod-id = "Bta0Pt47"
version = "fsavxtiv"

[option]
default = true
optional = true
description = """
Show bee info in inventory
\u80cc\u5305\u4e2d\u986f\u793a\u871c\u8702\u8cc7\u8a0a
"""
