name = "Better Mount HUD"
filename = "bettermounthud-1.1.4.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/kqJFAPU9/versions/1.1.4/bettermounthud-1.1.4.jar"
hash-format = "sha1"
hash = "60035cc1e9cf8bf880c42f57427719d773df5cd5"

[update]
[update.modrinth]
mod-id = "kqJFAPU9"
version = "MjGehyF4"

[option]
default = true
optional = true
description = """
Improves the ingame HUD while riding a mount
\u6539\u5584\u9a0e\u4e58\u6642\u754c\u9762
"""
