name = "Borderless Mining"
filename = "borderless-mining-1.1.2+1.18.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/kYq5qkSL/versions/1.1.2+1.18.2/borderless-mining-1.1.2%2B1.18.2.jar"
hash-format = "sha1"
hash = "2a7490d56d040529c86e0d1e4017cb825381bf78"

[update]
[update.modrinth]
mod-id = "kYq5qkSL"
version = "MJz6aK6t"

[option]
default = true
optional = true
description = """
Changes Fullscreen to use a borderless window
\u5168\u87a2\u5e55\u6539\u70ba\u7121\u908a\u6846\u8996\u7a97
"""
