name = "Carpet TIS Addition"
filename = "carpet-tis-addition-mc1.18.2-v1.44.0.jar"
side = "server"

[download]
hash-format = "sha1"
hash = "ccb9390393aa3f0f308937920eb83c53de74249c"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 4250817
project-id = 397510
