name = "Carpet TIS Addition"
filename = "carpet-tis-addition-mc1.18.2-v1.36.0.jar"
side = "server"

[download]
hash-format = "sha1"
hash = "0a75fbff762f3977d2ae3810b29ab9c96a2c9897"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3814610
project-id = 397510
