name = "Carpet TIS Addition"
filename = "carpet-tis-addition-mc1.18.2-v1.34.0.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3779/514/carpet-tis-addition-mc1.18.2-v1.34.0.jar"
hash-format = "sha1"
hash = "f575acf60cbe576eabd6b39eeaad979f6bce06cd"

[update]
[update.curseforge]
file-id = 3779514
project-id = 397510
