name = "Carpet TIS Addition"
filename = "carpet-tis-addition-mc1.18.2-v1.37.0.jar"
side = "server"

[download]
hash-format = "sha1"
hash = "69f322f57634d60b3fb79bef5263ea2d1fe0839d"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3829152
project-id = 397510
