name = "Carpet TIS Addition"
filename = "carpet-tis-addition-mc1.18.2-v1.35.0.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3786/181/carpet-tis-addition-mc1.18.2-v1.35.0.jar"
hash-format = "sha1"
hash = "4a5a399cbfd300b01d4f7150477b02b01c494ff5"

[update]
[update.curseforge]
file-id = 3786181
project-id = 397510
