name = "Carpet TIS Addition"
filename = "carpet-tis-addition-mc1.18.2-v1.32.2.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3750/124/carpet-tis-addition-mc1.18.2-v1.32.2.jar"
hash-format = "sha1"
hash = "89df7e5b43d1eccfbf0c1296459ce2bc0bae0caf"

[update]
[update.curseforge]
file-id = 3750124
project-id = 397510
