name = "Chat Lag Fix"
filename = "chatlagfix-1.16.5+1.17.1-2.1.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/fKi1znuF/versions/2.1.0/chatlagfix-1.16.5+1.17.1-2.1.0.jar"
hash-format = "sha1"
hash = "5fe378c73fad61e12bddacaa3eac730064f53a01"

[update]
[update.modrinth]
mod-id = "fKi1znuF"
version = "2DcOW6is"
