name = "CIT Resewn"
filename = "CITResewn-1.1.1+1.18.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/otVJckYQ/versions/1.1.1%2B1.18.2/CITResewn-1.1.1%2B1.18.2.jar"
hash-format = "sha1"
hash = "864c538f4f07bb43445ecdfb27e77649efaf4327"

[update]
[update.modrinth]
mod-id = "otVJckYQ"
version = "SwmQcI45"

[option]
optional = true
description = "Custom Item Texture with resource packs in Optifine format\n以資源包自定義 Optifine 式的物品材質\n"
default = true
