name = "ClearDespawn-Fabric"
filename = "cleardespawn-21w40a-1.1.3.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/yoJJjRRE/versions/21w40a-1.1.3/cleardespawn-21w40a-1.1.3.jar"
hash-format = "sha1"
hash = "3390baeaf6a9fe8f6e6120dbfc11cf231abf14dd"

[update]
[update.modrinth]
mod-id = "yoJJjRRE"
version = "9Xke6c1g"

[option]
default = true
optional = true
description = """
Dropped items flash when they're about to despawn
\u5373\u5c07\u6d88\u5931\u7684\u6389\u843d\u7269\u54c1\u6703\u9583\u720d\u63d0\u793a
"""
