name = "Click Opener Mod"
filename = "clickopener-1.0.1.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/sCRAcsAk/versions/1.0.1/clickopener-1.0.1.jar"
hash-format = "sha1"
hash = "cfaf497dbb2c5a81c2971d7c9e8f898ab356c0c2"

[update]
[update.modrinth]
mod-id = "sCRAcsAk"
version = "y4uNl8Ak"
