name = "Colormatic"
filename = "colormatic-3.1.2-pre.fix+mc.1.18.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/V4IQxkZC/versions/xI7F43eN/colormatic-3.1.2-pre.fix%2Bmc.1.18.2.jar"
hash-format = "sha1"
hash = "84fe9aea2b9451123fffbb74813c9f507513b3bc"

[update]
[update.modrinth]
mod-id = "V4IQxkZC"
version = "xI7F43eN"

[option]
optional = true
description = "Enables resource packs to add and change block and biome colors\n資源包可新增和變更方塊與生態域顏色\n"
default = true
