name = "Continuity"
filename = "continuity-1.1.0+1.17.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/1IjD5062/versions/1.1.0+1.17/continuity-1.1.0%2B1.17.jar"
hash-format = "sha1"
hash = "b82e709c8cf09e41a0fd7a312137030f7824c112"

[update]
[update.modrinth]
mod-id = "1IjD5062"
version = "yiOF0F2t"

[option]
default = true
optional = true
description = """
-[Recommended]-
Connect block texture
\u3010\u63a8\u85a6\u3011
\u9023\u63a5\u65b9\u584a\u6750\u8cea
"""
