name = "Couplings"
filename = "Couplings-1.8.1+1.18.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "c7d13c7308c8b6f3dcf8f38048bff45ca0f70b1f"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3816074
project-id = 311120

[option]
optional = true
description = "Open doors in pair\n(required in our server for best experience)\n同步開啟雙門\n(必須安裝以在伺服器獲得最佳體驗)\n"
default = true
