name = "Cull Leaves"
filename = "cullleaves-2.3.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/GNxdLCoP/versions/2.3.2/cullleaves-2.3.2.jar"
hash-format = "sha512"
hash = "e09a13efb20a36b7448fd3db688e2d810c00186a280be8f1e4ee2a1401267e544f981f8d8e042f15a00fef44abd9213a9eb46ffe3880b504c09ad5f5d532cf21"

[update]
[update.modrinth]
mod-id = "GNxdLCoP"
version = "718Klypf"

[option]
default = true
optional = true
description = """
-[Recommended]-
Leaves culling when too far from you
\u3010\u63a8\u85a6\u3011
\u592a\u9060\u7684\u6a39\u8449\u4e0d\u518d\u900f\u660e\uff0c\u53ef\u6539\u9032\u6027\u80fd
"""
