name = "Custom Entity Models (CEM)"
filename = "cem-0.7.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3709/988/cem-0.7.1.jar"
hash-format = "sha1"
hash = "cdee86c59231dbe6df3aa17cfa2041221346306b"

[update]
[update.curseforge]
file-id = 3709988
project-id = 477078

[option]
optional = true
default = false
description = """
Custom Enitity Model with resource packs in Optifine format (currently patially)
\u4ee5\u8cc7\u6e90\u5305\u81ea\u5b9a\u7fa9 Optifine \u5f0f\u7684\u751f\u7269\u6a21\u578b\uff0c\u76ee\u524d\u672a\u5b8c\u5584
"""
