name = "Custom Entity Models (CEM)"
filename = "cem-0.6.2.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3440/846/cem-0.6.2.jar"
hash-format = "murmur2"
hash = "3701570831"

[update]
[update.curseforge]
file-id = 3440846
project-id = 477078

[option]
optional = true
description = """
Custom Enitity Model with resource packs in Optifine format (currently patially)
\u4ee5\u8cc7\u6e90\u5305\u81ea\u5b9a\u7fa9 Optifine \u5f0f\u7684\u751f\u7269\u6a21\u578b\uff0c\u76ee\u524d\u672a\u5b8c\u5584
"""
