name = "Debugify"
filename = "debugify-1.11.0-fabric-1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/QwxR6Gcd/versions/1.11.0-fabric/debugify-1.11.0-fabric-1.18.2.jar"
hash-format = "sha1"
hash = "c1722e40c0592204e3664c482be3533fc185e578"
mode = ""

[update]
[update.modrinth]
mod-id = "QwxR6Gcd"
version = "ltSWiXrH"

[option]
optional = false
description = "Fix bugs in Minecarft to make the game smoother\n修復遊戲錯誤以獲得流暢體驗\n"
default = true
