name = "Debugify"
filename = "debugify-fabric-1.7.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/QwxR6Gcd/versions/1.7.2-fabric/debugify-fabric-1.7.2.jar"
hash-format = "sha1"
hash = "35862761682ce273e9026072214855f06e1e2aee"

[update]
[update.modrinth]
mod-id = "QwxR6Gcd"
version = "CSWmF24f"

[option]
optional = true
description = "-[Recommended]-\nFix bugs in Minecarft to make the game smoother\n【推薦】\n修復遊戲錯誤以獲得流暢體驗\n"
default = true
