name = "Debugify"
filename = "debugify-1.9.0-fabric-1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/QwxR6Gcd/versions/1.9.0-fabric/debugify-1.9.0-fabric-1.18.2.jar"
hash-format = "sha1"
hash = "8bc0a0baa76712718ab5334dcbef2a92dad3438b"

[update]
[update.modrinth]
mod-id = "QwxR6Gcd"
version = "rKzPCLMb"

[option]
optional = false
default = true
description = """
Fix bugs in Minecarft to make the game smoother
\u4fee\u5fa9\u904a\u6232\u932f\u8aa4\u4ee5\u7372\u5f97\u6d41\u66a2\u9ad4\u9a57
"""
