name = "Debugify"
filename = "debugify-fabric-1.7.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/QwxR6Gcd/versions/1.7.1-fabric/debugify-fabric-1.7.1.jar"
hash-format = "sha1"
hash = "8c6f94f33852f283de6546d8537b1c72d800ee0a"

[update]
[update.modrinth]
mod-id = "QwxR6Gcd"
version = "hY3DKYio"

[option]
optional = true
description = "-[Recommended]-\nFix bugs in Minecarft to make the game smoother\n【推薦】\n修復遊戲錯誤以獲得流暢體驗\n"
default = true
