name = "Discerning Furnace"
filename = "discerning-furnace-1.0.5+MC1.18-1.18.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/G3Nz6HN4/versions/1.0.5+MC1.18-1.18.1/discerning-furnace-1.0.5+MC1.18-1.18.1.jar"
hash-format = "sha1"
hash = "62bcaa36ffbdaba1abae45afe348d866d71e9b01"

[update]
[update.modrinth]
mod-id = "G3Nz6HN4"
version = "gHuD3XrQ"
