name = "Distant Horizons"
filename = "DistantHorizons-1.6.3a-1.18.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/uCdwusMi/versions/1.6.3a-1.18.2/DistantHorizons-1.6.3a-1.18.2.jar"
hash-format = "sha1"
hash = "b3da024bf73951522b287ea41ce9763589275703"

[update]
[update.modrinth]
mod-id = "uCdwusMi"
version = "qLXa9pDD"

[option]
optional = true
description = """
Extremely great performance with larger render distance
(Ignored by Iris shaders now)
\u589e\u5927\u6e32\u67d3\u8ddd\u96e2\u540c\u6642\u4fdd\u7559\u826f\u597d\u6027\u80fd
(\u76ee\u524d Iris \u5149\u5f71\u7121\u8996\u6b64 Mod)
"""
