name = "Distant Horizons"
filename = "DistantHorizons-neoforge-fabric-2.3.2-b-1.21.4.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/uCdwusMi/versions/94McsAoL/DistantHorizons-neoforge-fabric-2.3.2-b-1.21.4.jar"
hash-format = "sha512"
hash = "f5c16f004b708251d1442c95728defb938de23d3bb21c060042c2b761544d859fb31019db418ceda190d4c97ed8ecd7e03f2fabfcb406c6a01156a6525da0911"

[update]
[update.modrinth]
mod-id = "uCdwusMi"
version = "94McsAoL"

[option]
optional = true
description = "Extremely great performance with larger render distance\n(Ignored by Iris shaders now)\n增大渲染距離同時保留良好性能\n(目前 Iris 光影無視此 Mod)\n"
