name = "Distant Horizons"
filename = "DistantHorizons-1.6.5a-1.18.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/uCdwusMi/versions/1.6.5a-1.18.2/DistantHorizons-1.6.5a-1.18.2.jar"
hash-format = "sha1"
hash = "f83771589e1e7696c93c43dd7b94bc054672a4da"

[update]
[update.modrinth]
mod-id = "uCdwusMi"
version = "8ctYpkCM"

[option]
optional = true
description = "Extremely great performance with larger render distance\n(Ignored by Iris shaders now)\n增大渲染距離同時保留良好性能\n(目前 Iris 光影無視此 Mod)\n"
