name = "Dynamic View[Forge/Fabric]"
filename = "dynview.fabric-1.18.2-2.1.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3758/57/dynview.fabric-1.18.2-2.1.jar"
hash-format = "sha1"
hash = "94437b40fd46dbdd5f5b29f6b26b04873b79c6e3"

[update]
[update.curseforge]
file-id = 3758057
project-id = 366140
