name = "Ears (+ Snouts/Muzzles, Tails, Horns, Wings, and More)"
filename = "ears-fabric-1.17-1.4.5_01.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/mfzaZK3Z/versions/1.4.5_01+fabric-1.17.01/ears-fabric-1.17-1.4.5_01.jar"
hash-format = "sha1"
hash = "d23a54ec68240b81666aa444bdbf08cd6f0152f3"

[update]
[update.modrinth]
mod-id = "mfzaZK3Z"
version = "7AcIEmmQ"

[option]
default = true
optional = true
description = """
-[Recommended]-
Able to add more features to your skin when others installed
\u3010\u63a8\u85a6\u3011
\u53ef\u4ee5\u5728 Skin (\u76ae\u819a) \u88cf\u589e\u52a0\u66f4\u591a\u7279\u5fb5\uff0c\u5176\u4ed6\u6709\u5b89\u88dd\u6a21\u7d44\u7684\u4eba\u90fd\u80fd\u770b\u5230
"""
