name = "Eating Animation [Fabric]"
filename = "eating-animation-1.6.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3748/909/eating-animation-1.6.jar"
hash-format = "sha1"
hash = "bda6f2dbb141e6240fed1855d61a2d5e70d5ba4f"

[update]
[update.curseforge]
file-id = 3748909
project-id = 527023

[option]
default = false
optional = true
description = """
Add sprite animation for eating or drinking
\u65b0\u589e\u9032\u98df\u8cbc\u5716\u52d5\u756b
"""
