name = "Enhanced Block Entities"
filename = "enhancedblockentities-0.7+1.18.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/OVuFYfre/versions/0.7+1.18.2/enhancedblockentities-0.7%2B1.18.2.jar"
hash-format = "sha1"
hash = "bd318830b4aa5767a0fe1acc246ef3c07fd53282"

[update]
[update.modrinth]
mod-id = "OVuFYfre"
version = "5FTTHyNq"

[option]
optional = false
description = "Enhance rendering fo some blocks, like chest\n優化部份方塊的渲染，如箱子等\n"
default = true
