name = "Entity Texture Features [Fabric]"
filename = "entity-texture-features-beta-2.6.4-mc1.18.x.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/BVzZfTc1/versions/2.6.4/entity-texture-features-beta-2.6.4-mc1.18.x.jar"
hash-format = "sha1"
hash = "e91e1c1ee3da6e69be07f4cf09e466841bcc752f"

[update]
[update.modrinth]
mod-id = "BVzZfTc1"
version = "OL9wO7bF"

[option]
optional = true
description = "Support emissive, random & custom texture support for entities in resourcepacks in Optifine format\n支持 Optifine 式發光、隨機、自定義生物材質\n"
default = true
