name = "Entity Texture Features [Fabric]"
filename = "entity-texture-features-3.0.0-mc1.18.x.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/BVzZfTc1/versions/3.0.0/entity-texture-features-3.0.0-mc1.18.x.jar"
hash-format = "sha1"
hash = "ccb1bb691229a1204799da5c8e2e59ba23ea0509"
mode = ""

[update]
[update.modrinth]
mod-id = "BVzZfTc1"
version = "nYzDnjGu"

[option]
optional = true
description = "Support emissive, random & custom texture support for entities in resourcepacks in Optifine format\n支持 Optifine 式發光、隨機、自定義生物材質\n"
default = true
