name = "Entity Texture Features [Fabric]"
filename = "entity-texture-features-3.1.2-mc1.18.x.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/BVzZfTc1/versions/3.1.2-mc1.18/entity-texture-features-3.1.2-mc1.18.x.jar"
hash-format = "sha1"
hash = "a486ed982fe38a3a40859666039c5700ff7f97c5"

[update]
[update.modrinth]
mod-id = "BVzZfTc1"
version = "papGjlzO"

[option]
optional = true
description = "Support emissive, random & custom texture support for entities in resourcepacks in Optifine format\n支持 Optifine 式發光、隨機、自定義生物材質\n"
default = true
