name = "Entity Culling Fabric/Forge"
filename = "entityculling-fabric-mc1.18-1.5.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3743/933/entityculling-fabric-mc1.18-1.5.1.jar"
hash-format = "sha1"
hash = "523c57485a469c581d7a9bd18ec86c7a92a0ec93"

[update]
[update.curseforge]
file-id = 3743933
project-id = 448233

[option]
optional = true
default = true
description = """
-[Recommended]-
Entity culling when not visible.
\u3010\u63a8\u85a6\u3011
\u770b\u4e0d\u5230\u7684\u751f\u7269\u4e0d\u518d\u6e32\u67d3\uff0c\u53ef\u6539\u9032\u6027\u80fd
"""
