name = "Fabrishot"
filename = "fabrishot-1.7.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/3qsfQtE9/versions/1.7.0/fabrishot-1.7.0.jar"
hash-format = "sha1"
hash = "343f31455c666b3979026d8a983abfa9c8ca0c9e"

[update]
[update.modrinth]
mod-id = "3qsfQtE9"
version = "MydLWyXb"

[option]
default = true
optional = true
description = """
Screenshot in other resolution
\u4ee5\u5176\u4ed6\u89e3\u6790\u5ea6\u622a\u5716
"""
