name = "Fabric API"
filename = "fabric-api-0.56.0+1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.56.0+1.18.2/fabric-api-0.56.0%2B1.18.2.jar"
hash-format = "sha1"
hash = "cda8c4d6c0ab42efbc2e5c10ad06cbab563bc728"

[update]
[update.modrinth]
mod-id = "P7dR8mSH"
version = "jqrQwxen"
