name = "Fabric API"
filename = "fabric-api-0.53.0+1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.53.0+1.18.2/fabric-api-0.53.0%2B1.18.2.jar"
hash-format = "sha1"
hash = "9763a1588fe73c36a4d15f98d974240ec7e5ad6b"

[update]
[update.modrinth]
mod-id = "P7dR8mSH"
version = "UxKTFgii"
