name = "FabricSkyboxes"
filename = "fabricskyboxes-1.18.2-0.5.5.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/YBz7DOs8/versions/0.5.5/fabricskyboxes-1.18.2-0.5.5.jar"
hash-format = "sha1"
hash = "bf5e74b5e3ae3b9b945c11e2fdc0477490f26f4c"

[update]
[update.modrinth]
mod-id = "YBz7DOs8"
version = "m8fbq5qt"

[option]
default = false
optional = true
description = """
Custom sky texture with resource packs in Optifine format
\u4ee5\u8cc7\u6e90\u5305\u81ea\u5b9a\u7fa9 Optifine \u5f0f\u7684\u5929\u7a7a\u6750\u8cea
"""
