name = "Farsight [Fabric]"
filename = "farsight.fabric-1.18-1.9.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3778/514/farsight.fabric-1.18-1.9.jar"
hash-format = "sha1"
hash = "c67b60eeef67c9acd69da7ac49e87cf324c4802c"

[update]
[update.curseforge]
file-id = 3778514
project-id = 579192

[option]
optional = true
description = """
Caching map to increase view distance on client-side
\u589e\u52a0\u986f\u793a\u8ddd\u96e2\uff0c\u6703\u4e0b\u8f09\u6240\u7d93\u904e\u7684\u5730\u5716\u4f86\u66ff\u4ee3\u4f3a\u670d\u5668\u8ddd\u96e2\u9650\u5236\u5916\u7684\u5730\u65b9
"""
