name = "FastGrowth"
filename = "fastgrowth-1.6.1.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/Snyv7ZEw/versions/1.6.1/fastgrowth-1.6.1.jar"
hash-format = "sha1"
hash = "d53d7bc48a7becd935c1faef2b498711447d19f6"

[update]
[update.modrinth]
mod-id = "Snyv7ZEw"
version = "WkNMzAyL"
