name = "ForgetMeChunk"
filename = "forgetmechunk-1.17.X-1.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3706/27/forgetmechunk-1.17.X-1.0.3.jar"
hash-format = "sha1"
hash = "c34d28ab3e485350579c3ed2546d27c34193b701"

[update]
[update.curseforge]
file-id = 3706027
project-id = 591317

[option]
optional = true
default = true
description = """
-[Recommended]-
Reduce laging in some situation, may cause bug
\u3010\u63a8\u85a6\u3011
\u6e1b\u5c11\u67d0\u4e9b\u60c5\u6cc1\u7684\u5361\u9813\uff0c\u6709\u6a5f\u6703\u6709 bug
"""
