name = "Grind Enchantments"
filename = "grind-enchantments-1.6.4+1.18.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "11c1b497e3fd7b2de76ecdbe9650036a83d561f3"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3826189
project-id = 379680

[option]
optional = true
description = "Able to use grinder to move enchantment between items\n(required in our server for best experience)\n以砂輪移動物品中的附魔\n(必須安裝以在伺服器獲得最佳體驗)\n"
default = true
