name = "Grind Enchantments"
filename = "grind-enchantments-1.6.3+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3763/959/grind-enchantments-1.6.3+1.18.2.jar"
hash-format = "sha1"
hash = "e4d5aa067b9f3f5c863406b696c9b66b5b7e39d7"

[update]
[update.curseforge]
file-id = 3763959
project-id = 379680

[option]
optional = true
description = """
Able to use grinder to move enchantment between items
(required in our server for best experience)
\u4ee5\u7802\u8f2a\u79fb\u52d5\u7269\u54c1\u4e2d\u7684\u9644\u9b54
(\u5fc5\u9808\u5b89\u88dd\u4ee5\u5728\u4f3a\u670d\u5668\u7372\u5f97\u6700\u4f73\u9ad4\u9a57)
"""
default = true
