name = "Grind Enchantments"
filename = "grind-enchantments-1.6.2+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3745/738/grind-enchantments-1.6.2+1.18.2.jar"
hash-format = "sha1"
hash = "23e7595975de43dba2602eef66c000d3d9971841"

[update]
[update.curseforge]
file-id = 3745738
project-id = 379680

[option]
optional = true
description = "-[Recommended]-\nAble to use grinder to move enchantment between items\n(required in our server for best experience)\n【推薦】\n以砂輪移動物品中的附魔\n(必須安裝以在伺服器獲得最佳體驗)\n"
default = true
