name = "Grind Enchantments"
filename = "grind-enchantments-1.6.3+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3763/959/grind-enchantments-1.6.3+1.18.2.jar"
hash-format = "sha1"
hash = "e4d5aa067b9f3f5c863406b696c9b66b5b7e39d7"

[update]
[update.curseforge]
file-id = 3763959
project-id = 379680

[option]
optional = true
description = "-[Recommended]-\nAble to use grinder to move enchantment between items\n(required in our server for best experience)\n【推薦】\n以砂輪移動物品中的附魔\n(必須安裝以在伺服器獲得最佳體驗)\n"
default = true
