name = "Hat List"
filename = "hatlist-1.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/nHLxbmEC/versions/1.2/hatlist-1.2.jar"
hash-format = "sha1"
hash = "792d7412c35399c512771435a3ed22f89d198fbc"

[update]
[update.modrinth]
mod-id = "nHLxbmEC"
version = "LZeQHBFR"

[option]
optional = false
default = true
description = """
Show hat in tab list
\u73a9\u5bb6\u5217\u8868\u4e2d\u986f\u793a\u5e3d\u5b50
"""
