name = "Indium"
filename = "indium-1.0.3+mc1.18.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/Orvt0mRa/versions/1.0.3+mc1.18.2/indium-1.0.3%2Bmc1.18.2.jar"
hash-format = "sha1"
hash = "a20793e65789fb9ef248d07dfd2fcd79e8afb53d"

[update]
[update.modrinth]
mod-id = "Orvt0mRa"
version = "ZxoJeTLg"

[option]
optional = false
description = """
Compatibility layer for Sodium when using other decorating mods
Sodium \u7684\u76f8\u5bb9\u5c64\uff0c\u7528\u4ee5\u76f8\u5bb9\u5176\u4ed6\u88dd\u98fe\u6a21\u7d44
"""
default = true
