name = "Infinity Fix"
filename = "infinity-fix-0.1.3.jar"
side = "both"

[download]
url = "https://kuko.ooo/packwiz-packs/mods/infinity-fix-0.1.3.jar"
hash-format = "sha1"
hash = "31734805797a17be37fcf62155153a335b9b7f02"

[update]
[update.modrinth]
mod-id = "zFWme3NP"
version = "sDLrDpDG"
