name = "Infinity Fix"
filename = "infinity-fix-0.1.4.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/zFWme3NP/versions/v0.1.4/infinity-fix-0.1.4.jar"
hash-format = "sha1"
hash = "51df307eebf45e58cbf5a186b3d1402ee5e7d66a"

[update]
[update.modrinth]
mod-id = "zFWme3NP"
version = "bU0ko84G"
