name = "Iris Shaders"
filename = "iris-mc1.18.2-1.2.3-build.35.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/YL57xq9U/versions/1.18.x-v1.2.3/iris-mc1.18.2-1.2.3-build.35.jar"
hash-format = "sha1"
hash = "54f32b6beaa5bfb3bbfde8eacd615b2ddcec1fca"

[update]
[update.modrinth]
mod-id = "YL57xq9U"
version = "XU7Kt1A6"

[option]
optional = true
default = true
description = """
Shader mod that compatible with some of the Optifine shaders
\u517c\u5bb Optifine \u5149\u5f71\u5305\u7684\u6a21\u7d44
"""
