name = "Iris Shaders"
filename = "iris-mc1.17.1-1.2.3-build.34.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/YL57xq9U/versions/1.17.x-v1.2.3/iris-mc1.17.1-1.2.3-build.34.jar"
hash-format = "sha1"
hash = "e1ac3311ba51b55e00f269fd0002f602deeb8a39"

[update]
[update.modrinth]
mod-id = "YL57xq9U"
version = "nwP12ckH"

[option]
optional = true
description = "-[Recommended]-\nShader mod that compatible with some of the Optifine shaders\n【推薦】\n兼容 Optifine 光影包的模組\n"
