name = "Iris Shaders"
filename = "iris-mc1.17.1-1.2.2-build.31.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/YL57xq9U/versions/1.17.x-v1.2.2/iris-mc1.17.1-1.2.2-build.31.jar"
hash-format = "sha1"
hash = "004188eaa6952ca579685e7d79d24bf8f2067638"

[update]
[update.modrinth]
mod-id = "YL57xq9U"
version = "7GHcCn6V"

[option]
optional = true
description = """
-[Recommended]-
Shader mod that compatible with some of the Optifine shaders
\u3010\u63a8\u85a6\u3011
\u517c\u5bb9 Optifine \u5149\u5f71\u5305\u7684\u6a21\u7d44
"""
