name = "Iris Shaders"
filename = "iris-mc1.18.2-1.2.5.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/YL57xq9U/versions/1.18.x-v1.2.5/iris-mc1.18.2-1.2.5.jar"
hash-format = "sha1"
hash = "57237aeaff64a362b7b1695e18c42317d3bcf374"

[update]
[update.modrinth]
mod-id = "YL57xq9U"
version = "M18bSfGf"

[option]
optional = true
description = "Shader mod that compatible with some of the Optifine shaders\n兼容 Optifine 光影包的模組\n"
default = true
