name = "lazy-language-loader"
filename = "lazy-language-loader-0.3.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/Nz0RSWrF/versions/0.3.0/lazy-language-loader-0.3.0.jar"
hash-format = "sha1"
hash = "305a2f59667ae14efbfd11eca21aa30220ee764b"

[update]
[update.modrinth]
mod-id = "Nz0RSWrF"
version = "dlxs43xF"

[option]
optional = false
default = true
description = """
Language loading optimization
\u8a9e\u8a00\u8f09\u5165\u512a\u5316
"""
