name = "LazyDFU"
filename = "lazydfu-0.1.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/hvFnDODi/versions/0.1.2/lazydfu-0.1.2.jar"
hash-format = "sha1"
hash = "2efec5781f1271bdcdae462eee402ccb97bff6fe"

[update]
[update.modrinth]
mod-id = "hvFnDODi"
version = "C6e265zK"

[option]
optional = true
default = true
description = """
-[Recommended]-
Load map update code on-demand to speed up launching speed
\u3010\u63a8\u85a6\u3011
\u52a0\u5feb\u8f09\u5165\u901f\u5ea6\uff0c\u6309\u9700\u8f09\u5165\u5730\u5716\u5347\u7d1a\u4ee3\u78bc
"""
