name = "Litematica"
filename = "litematica-fabric-1.18.2-0.11.2.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3751/645/litematica-fabric-1.18.2-0.11.2.jar"
hash-format = "sha1"
hash = "8d3faf150dd06a5955a9f81637871716a983d4b3"

[update]
[update.curseforge]
file-id = 3751645
project-id = 308892

[option]
optional = true
description = """
Blueprint mod that helps you building
\u5efa\u7bc9\u85cd\u5716\u6a21\u7d44
"""
