name = "Lithium"
filename = "lithium-fabric-mc1.18.2-0.7.9.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/gvQqBUqZ/versions/mc1.18.2-0.7.9/lithium-fabric-mc1.18.2-0.7.9.jar"
hash-format = "sha1"
hash = "2f0298476ba54e8fc640c9bfe132a193db45b92b"

[update]
[update.modrinth]
mod-id = "gvQqBUqZ"
version = "MoF1cn6g"

[option]
optional = true
default = true
description = """
-[Recommended]-
Server optimization
\u3010\u63a8\u85a6\u3011
\u4f3a\u670d\u5668\u512a\u5316
"""
