name = "MiniHUD"
filename = "minihud-fabric-1.18.2-0.22.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3671/392/minihud-fabric-1.18.2-0.22.0.jar"
hash-format = "sha1"
hash = "dc85e2befc102c9260f6eebeb72317043ce6530a"

[update]
[update.curseforge]
file-id = 3671392
project-id = 244260

[option]
optional = true
default = false
description = """
More HUD in-game, like lighting values of each blocks
\u66f4\u591a\u904a\u6232\u8cc7\u8a0a\u986f\u793a\uff0c\u5982\u65b9\u584a\u4eae\u5ea6
"""
