name = "MiniHUD"
filename = "minihud-fabric-1.18.2-0.22.1.jar"
side = "client"

[download]
hash-format = "sha1"
hash = "b8101d801f8625b03d61707997b3a27197375785"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3909308
project-id = 244260

[option]
optional = true
description = "More HUD in-game, like lighting values of each blocks\n更多遊戲資訊顯示，如方塊亮度\n"
