name = "Monsters in the Closet"
filename = "monsters-in-the-closet-1.0.3+1.18.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3672/715/monsters-in-the-closet-1.0.3+1.18.jar"
hash-format = "sha1"
hash = "13f57612fb0389b45627e053f7d60a69c0cbb8e0"

[update]
[update.curseforge]
file-id = 3672715
project-id = 429222
