name = "Ok Zoomer"
filename = "okzoomer-5.0.0-beta.3+1.17.1.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/aXf2OSFU/versions/5.0.0-beta.3+1.17.1/okzoomer-5.0.0-beta.3+1.17.1.jar"
hash-format = "sha1"
hash = "aa493f41d89b2a1e1a299ae4ee8073ad39f67dca"

[update]
[update.modrinth]
mod-id = "aXf2OSFU"
version = "esyBJPbU"

[option]
default = true
optional = true
description = """
-[Recommended]-
Zoom in-game
\u3010\u63a8\u85a6\u3011
\u653e\u5927\u93e1
"""
