name = "OverpoweredMending"
filename = "OverpoweredMending-1.18.2-2.4.3.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/DKzFWXbg/versions/BGQzS6cB/OverpoweredMending-1.18.2-2.4.3.jar"
hash-format = "sha1"
hash = "7c0ac34b91cc1f0f8e534b2ecdb33ec0b0177e50"

[update]
[update.modrinth]
mod-id = "DKzFWXbg"
version = "BGQzS6cB"
