name = "ParadoxSlabs"
filename = "paradox-slabs-0.1.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/MxPkW0zr/versions/0.1.2/paradox-slabs-0.1.2.jar"
hash-format = "sha1"
hash = "becf197f0cc092d1823f60e45ee6dd543167d531"

[update]
[update.modrinth]
mod-id = "MxPkW0zr"
version = "waaek9RC"

[option]
optional = true
default = true
description = """
Independently destroy slabs in a block
(required in our server for best experience)
\u5206\u5225\u7834\u58de\u534a\u78da
(\u5fc5\u9808\u5b89\u88dd\u4ee5\u5728\u4f3a\u670d\u5668\u7372\u5f97\u6700\u4f73\u9ad4\u9a57)
"""
