name = "ParadoxSlabs"
filename = "paradox-slabs-0.1.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/MxPkW0zr/versions/0.1.1/paradox-slabs-0.1.1.jar"
hash-format = "sha512"
hash = "a748f6dae320d570b1eb15ed7a625ce8b46f032d05655c7628ebc220aaf9e4bdc04354151d73bf534756a7cf96a3032ce7f73a1d3a231433ee27a4a05ec83d0d"

[update]
[update.modrinth]
mod-id = "MxPkW0zr"
version = "gMH1HOAC"

[option]
default = true
optional = true
description = """
-[Recommended]-
Independently destroy slabs in a block
(required in our server for best experience)
\u3010\u63a8\u85a6\u3011
\u5206\u5225\u7834\u58de\u534a\u78da
(\u5fc5\u9808\u5b89\u88dd\u4ee5\u5728\u4f3a\u670d\u5668\u7372\u5f97\u6700\u4f73\u9ad4\u9a57)
"""
