name = "Puzzle"
filename = "puzzle-1.4.1-1.18.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/3IuO68q1/versions/EZrDjvh2/puzzle-1.4.1-1.18.jar"
hash-format = "sha1"
hash = "a630f54c71b7bf43999a41b37763f245a2687f5f"

[update]
[update.modrinth]
mod-id = "3IuO68q1"
version = "EZrDjvh2"

[option]
optional = true
description = "Adds resourcepack features and a GUI to more conveniently configure OptiFine alternatives\n新增資源包功能和方便控制部份美化模組的界面\n"
default = true
