name = "Puzzle"
filename = "puzzle-1.3.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/3IuO68q1/versions/1.3.0/puzzle-1.3.0.jar"
hash-format = "sha1"
hash = "0fc7706f450418c09c4a2ffddbbbd2ccdebcf31a"

[update]
[update.modrinth]
mod-id = "3IuO68q1"
version = "ILWsnRId"

[option]
optional = true
description = "Adds resourcepack features and a GUI to more conveniently configure OptiFine alternatives\n新增資源包功能和方便控制部份美化模組的界面\n"
default = true
