name = "ResolutionControl+"
filename = "resolution-control-plus-3.0.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3354/692/resolution-control-plus-3.0.0.jar"
hash-format = "sha1"
hash = "983b3aadcad74ea41a80c721a4194be1117597ba"

[update]
[update.curseforge]
file-id = 3354692
project-id = 446974

[option]
default = true
optional = true
description = """
Change rendering resolution, and screenshot in other size
\u8b8a\u66f4\u6e32\u67d3\u89e3\u6790\u5ea6\uff0c\u4e26\u4ee5\u5176\u4ed6\u89e3\u6790\u5ea6\u622a\u5716
"""
