name = "Semblance"
filename = "semblance-1.1.1.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/FFiEdqAn/versions/1.1.1/semblance-1.1.1.jar"
hash-format = "sha1"
hash = "44644ae484e2660d5235669a25dafac65522c4fc"

[update]
[update.modrinth]
mod-id = "FFiEdqAn"
version = "NseOHWfb"
