name = "ShulkerBoxTooltip [Fabric/Forge]"
filename = "shulkerboxtooltip-fabric-3.1.3+1.18.2.jar"
side = "client"

[download]
hash-format = "sha1"
hash = "fa2aeca65e641fae79321e6961e4f95f8f05b64d"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 4032072
project-id = 315811

[option]
optional = true
description = "Preview shulker boxes in inventory\n背包中預覽界伏盒\n"
default = true
