name = "Smoke Suppression"
filename = "smoke-suppression-1.0.9-1+MC1.18-1.18.2.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3694/152/smoke-suppression-1.0.9-1+MC1.18-1.18.2.jar"
hash-format = "sha1"
hash = "9d91b675d1dca8d4367f2f0a92f14fc6838eb68b"

[update]
[update.curseforge]
file-id = 3694152
project-id = 440468

[option]
optional = true
default = true
description = """
Suppress smoke of campfires in farms, improving performance
\u5237\u602a\u5854\u7684\u71df\u706b\u4e0d\u518d\u5192\u7159\uff0c\u6539\u9032\u6027\u80fd
"""
