name = "Smoke Suppression"
filename = "smoke-suppression-1.2.2+MC1.21.2-1.21.5.jar"
side = "client"

[download]
hash-format = "sha1"
hash = "407a54c7b8546c6de43455e74e0abc4c4e3871c9"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 6368111
project-id = 440468

[option]
optional = true
description = "Suppress smoke of campfires in farms, improving performance\n刷怪塔的營火不再冒煙，改進性能\n"
default = true
