name = "Smoke Suppression"
filename = "smoke-suppression-1.2.1+MC1.21.2-1.21.4.jar"
side = "client"

[download]
hash-format = "sha1"
hash = "777e7ae600791812bcd1b60110956debb47b69d4"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 6000774
project-id = 440468

[option]
optional = true
description = "Suppress smoke of campfires in farms, improving performance\n刷怪塔的營火不再冒煙，改進性能\n"
default = true
