name = "Smooth Chunk Save[Forge/Fabric]"
filename = "smoothchunk-fabric-1.18.2-1.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3760/283/smoothchunk-fabric-1.18.2-1.8.jar"
hash-format = "sha1"
hash = "71edb53f3c580ce6cd1b5b5dd811334792cfb23b"

[update]
[update.curseforge]
file-id = 3760283
project-id = 582327

[option]
default = true
optional = true
description = """
Saves chunks continuously over time, instead of save at once with lagspikes
\u6301\u7e8c\u5730\u5132\u5b58\u5340\u584a\uff0c\u907f\u514d\u4e00\u6b21\u5132\u5b58\u5168\u90e8\u800c\u5361\u9813
"""
