name = "Sodium Extra"
filename = "sodium-extra-mc1.18.2-0.4.3.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/PtjYWJkn/versions/mc1.18.2-0.4.3/sodium-extra-mc1.18.2-0.4.3.jar"
hash-format = "sha1"
hash = "026226ee3777ee0dc1226b843271447afc551349"

[update]
[update.modrinth]
mod-id = "PtjYWJkn"
version = "i2Nmjt90"

[option]
optional = true
default = true
description = """
-[Recommended]-
More option in Sodium
\u3010\u63a8\u85a6\u3011
Sodium \u66f4\u591a\u9078\u9805
"""
