name = "Sodium Extra"
filename = "sodium-extra-mc1.17.1-0.4.3.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/PtjYWJkn/versions/mc1.17.1-0.4.3/sodium-extra-mc1.17.1-0.4.3.jar"
hash-format = "sha1"
hash = "debfd7204ccffefc22be32e0551bc289dbfa17d4"

[update]
[update.modrinth]
mod-id = "PtjYWJkn"
version = "94EgQDeg"

[option]
optional = true
default = true
description = """
-[Recommended]-
More option in Sodium
\u3010\u63a8\u85a6\u3011
Sodium \u66f4\u591a\u9078\u9805
"""
