name = "Starlight (Fabric)"
filename = "starlight-1.0.0+fabric.73f6d37.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/H8CaAYZC/versions/Starlight 1.0.0 1.17.x/starlight-1.0.0+fabric.73f6d37.jar"
hash-format = "sha512"
hash = "e2308963e019f030b804e787f9996044e12a63436754def273b79063b1ba3c99dc7311acbe99edab9dab290da97a75ac67e99715f485bc04d9e13e75a6a6644e"

[update]
[update.modrinth]
mod-id = "H8CaAYZC"
version = "nc7qGadJ"

[option]
default = true
optional = true
description = """
-[Recommended]-
Optimize light calculation
\u3010\u63a8\u85a6\u3011
\u512a\u5316\u5149\u7167\u8a08\u7b97
"""
