name = "Starlight (Fabric)"
filename = "starlight-1.0.2+fabric.89b8d9f.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/H8CaAYZC/versions/1.0.2+1.18.2/starlight-1.0.2+fabric.89b8d9f.jar"
hash-format = "sha1"
hash = "a436b72ee514bd2b59900159bcc4d461f96ef340"

[update]
[update.modrinth]
mod-id = "H8CaAYZC"
version = "4ew9whL8"

[option]
optional = true
default = true
description = """
-[Recommended]-
Optimize light calculation
\u3010\u63a8\u85a6\u3011
\u512a\u5316\u5149\u7167\u8a08\u7b97
"""
