name = "Stendhal"
filename = "stendhal-1.3.1-1.18.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/BWloQ9jK/versions/1.3.1/stendhal-1.3.1-1.18.jar"
hash-format = "sha1"
hash = "a6de2a9487d13dbc48745be46e3b48279679c087"

[update]
[update.modrinth]
mod-id = "BWloQ9jK"
version = "mctIoo5p"

[option]
optional = true
description = "Advance writing interfaces for signs, books and others\n進階書寫界面，如告示牌、書本等\n"
