name = "Unlimited Dragon Eggs"
filename = "unlimiteddragoneggs-1.2.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/gPsFae0U/versions/1.3.1/unlimiteddragoneggs-1.2.1.jar"
hash-format = "sha1"
hash = "55fece6f17b35a078aab900bb018d7ac9b71ea59"

[update]
[update.modrinth]
mod-id = "gPsFae0U"
version = "lbqBiCJ1"
