name = "Unlimited Dragon Eggs"
filename = "unlimiteddragoneggs-1.2.1.jar"
side = "both"

[download]
url = "https://raw.githubusercontent.com/Small-Ku/packwiz-packs/tmp-file/unlimiteddragoneggs-1.2.1.jar"
hash-format = "sha1"
hash = "0d8395aaff4c5e74317e448857ec5a085a59d08d"

[update]
[update.modrinth]
mod-id = "gPsFae0U"
version = "lbqBiCJ1"
