name = "VTDownloader"
filename = "vt-downloader-1.0.6+1.18.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/1E2sq1cp/versions/1.0.6+1.18/vt-downloader-1.0.6+1.18.jar"
hash-format = "sha1"
hash = "769fd2a5096fe72f3c48cea4db2ac2a3d50d2502"

[update]
[update.modrinth]
mod-id = "1E2sq1cp"
version = "F3u72XMh"

[option]
default = false
optional = true
description = """
Download Vanilla Tweaks packs directly in-game for many enhancements
\u76f4\u63a5\u5728\u904a\u6232\u5167\u4e0b\u8f09 Vanilla Tweaks \u5404\u7a2e\u6539\u9032\u8cc7\u6e90\u5305
"""
