name = "Why Am I on Fire?"
filename = "whyamionfire-1.1.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/jwslX1Al/versions/1.1.2/whyamionfire-1.1.2.jar"
hash-format = "sha1"
hash = "4186af37644d9f89b2b1ceefb77addedbfdf0c69"

[update]
[update.modrinth]
mod-id = "jwslX1Al"
version = "lL2yBvG6"

[option]
optional = false
default = true
description = """
Remove the fire on screen in not intended situations
\u79fb\u9664\u83ab\u540d\u5176\u5999\u7684\u71c3\u71d2\u756b\u9762
"""
