name = "Wither Cage Fix"
filename = "wither-cage-fix-1.0.12+MC1.18-1.18.2.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/8tiZuCBJ/versions/1.0.12+MC1.18-1.18.2/wither-cage-fix-1.0.12%2BMC1.18-1.18.2.jar"
hash-format = "sha1"
hash = "def1ab5e50a904bf96ee08664bdeaeac1c9a7084"

[update]
[update.modrinth]
mod-id = "8tiZuCBJ"
version = "cdNqPQqv"
