name = "WorldEdit"
filename = "worldedit-mod-7.3.11.jar"
side = "server"

[download]
hash-format = "sha1"
hash = "0ed5b3d41e4d768ac84179e0c93c2ee796313e04"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 6338613
project-id = 225608
