name = "WTHIT"
filename = "wthit-fabric-4.9.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/6AQIaxuO/versions/fabric-4.9.0/wthit-fabric-4.9.0.jar"
hash-format = "sha1"
hash = "f8dae0ed10abcbfc105efc3478f19101ba1d1f26"

[update]
[update.modrinth]
mod-id = "6AQIaxuO"
version = "Yt5VkiMf"

[option]
optional = true
description = "-[Recommended]-\nShowing info of blocks or entities the cursor pointing\n【推薦】\n顯示畫面指向的方塊或生物資訊\n"
