name = "WTHIT"
filename = "wthit-fabric-4.10.1.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/6AQIaxuO/versions/fabric-4.10.1/wthit-fabric-4.10.1.jar"
hash-format = "sha1"
hash = "73e1fc50286a55c05cee837a8b93ef28a05fd04f"

[update]
[update.modrinth]
mod-id = "6AQIaxuO"
version = "f18HhgGL"

[option]
optional = true
description = "Showing info of blocks or entities the cursor pointing\n顯示畫面指向的方塊或生物資訊\n"
default = true
