name = "WTHIT"
filename = "wthit-fabric-4.11.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/6AQIaxuO/versions/fabric-4.11.0/wthit-fabric-4.11.0.jar"
hash-format = "sha1"
hash = "c26ef360f6246d0d13d7c19b7537548df2fa2212"

[update]
[update.modrinth]
mod-id = "6AQIaxuO"
version = "VN3y7YuP"

[option]
optional = true
description = "Showing info of blocks or entities the cursor pointing\n顯示畫面指向的方塊或生物資訊\n"
default = true
