name = "WTHIT"
filename = "wthit-fabric-4.9.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/6AQIaxuO/versions/fabric-4.9.0/wthit-fabric-4.9.0.jar"
hash-format = "sha1"
hash = "f8dae0ed10abcbfc105efc3478f19101ba1d1f26"

[update]
[update.modrinth]
mod-id = "6AQIaxuO"
version = "Yt5VkiMf"

[option]
optional = true
default = true
description = """
Showing info of blocks or entities the cursor pointing
\u986f\u793a\u756b\u9762\u6307\u5411\u7684\u65b9\u584a\u6216\u751f\u7269\u8cc7\u8a0a
"""
