name = "WTHIT"
filename = "wthit-fabric-4.8.1.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/6AQIaxuO/versions/fabric-4.8.1/wthit-fabric-4.8.1.jar"
hash-format = "sha1"
hash = "9345925ea8d6cff5dd6b60aa63abc24d711b580c"

[update]
[update.modrinth]
mod-id = "6AQIaxuO"
version = "BqOPOtTN"

[option]
optional = true
default = false
description = """
-[Recommended]-
Showing info of blocks or entities the cursor pointing
\u3010\u63a8\u85a6\u3011
\u986f\u793a\u756b\u9762\u6307\u5411\u7684\u65b9\u584a\u6216\u751f\u7269\u8cc7\u8a0a
"""
