name = "WTHIT"
filename = "wthit-fabric-4.10.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/6AQIaxuO/versions/fabric-4.10.0/wthit-fabric-4.10.0.jar"
hash-format = "sha1"
hash = "360c9f653b66dd4783a538bbffd311aeb0e1d742"

[update]
[update.modrinth]
mod-id = "6AQIaxuO"
version = "NzztmDS6"

[option]
optional = true
description = "Showing info of blocks or entities the cursor pointing\n\u986f\u793a\u756b\u9762\u6307\u5411\u7684\u65b9\u584a\u6216\u751f\u7269\u8cc7\u8a0a\n"
default = true
