name = "WTHIT"
filename = "wthit-fabric-4.10.3.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/6AQIaxuO/versions/fabric-4.10.3/wthit-fabric-4.10.3.jar"
hash-format = "sha1"
hash = "014f61ffa930eaf41dd48156e97dde63abe08327"

[update]
[update.modrinth]
mod-id = "6AQIaxuO"
version = "IPNj6sXo"

[option]
optional = true
description = "Showing info of blocks or entities the cursor pointing\n顯示畫面指向的方塊或生物資訊\n"
default = true
