name = "Xaero's Minimap"
filename = "Xaeros_Minimap_22.6.1_Fabric_1.17.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3761/735/Xaeros_Minimap_22.6.1_Fabric_1.17.1.jar"
hash-format = "sha1"
hash = "18c72b11a384a270b3a7df801f721edec83a4ffc"

[update]
[update.curseforge]
file-id = 3761735
project-id = 263420

[option]
optional = true
description = "-[Recommended]-\nMinimap\n【推薦】\n小地圖\n"
