name = "Xaero's Minimap"
filename = "Xaeros_Minimap_25.2.0_Fabric_1.21.4.jar"
side = "client"

[download]
hash-format = "sha1"
hash = "c348eed936f5e743e55e26910574713fb24f5749"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 6306200
project-id = 263420

[option]
optional = true
description = "Minimap\n小地圖\n"
default = true
