name = "Xaero's Minimap"
filename = "Xaeros_Minimap_22.7.0_Fabric_1.18.2.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3778/435/Xaeros_Minimap_22.7.0_Fabric_1.18.2.jar"
hash-format = "sha1"
hash = "8da460edf35c55bb77bc9f240c1d431a8de52cd9"

[update]
[update.curseforge]
file-id = 3778435
project-id = 263420

[option]
optional = true
description = """
Minimap
\u5c0f\u5730\u5716
"""
default = true
