name = "Xaero's World Map"
filename = "XaerosWorldMap_1.21.0_Fabric_1.18.2.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3778/447/XaerosWorldMap_1.21.0_Fabric_1.18.2.jar"
hash-format = "sha1"
hash = "cad590bc0e7af4e4353fc5c128157b6ac5d21d3e"

[update]
[update.curseforge]
file-id = 3778447
project-id = 317780

[option]
optional = true
description = """
World Map
\u4e16\u754c\u5730\u5716
"""
default = true
