name = "Xaero's Minimap"
filename = "Xaeros_Minimap_22.6.1_Fabric_1.18.2.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3761/736/Xaeros_Minimap_22.6.1_Fabric_1.18.2.jar"
hash-format = "sha1"
hash = "c5c9e67baff2fe8ba89ab2282e61a4d5f15ba0a1"

[update]
[update.curseforge]
file-id = 3761736
project-id = 263420

[option]
optional = true
default = true
description = """
Minimap
\u5c0f\u5730\u5716
"""
