name = "Xaero's World Map"
filename = "XaerosWorldMap_1.20.7_Fabric_1.17.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3761/740/XaerosWorldMap_1.20.7_Fabric_1.17.1.jar"
hash-format = "sha1"
hash = "8f21047fd6d81fc6c8a224eae3a505b96272526e"

[update]
[update.curseforge]
file-id = 3761740
project-id = 317780

[option]
optional = true
description = "-[Recommended]-\nWorld Map\n【推薦】\n世界地圖\n"
