name = "1.17.1 for friends"
author = "Small-Ku"
version = "0.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eeb9c90f1a525f42973379c65213330ab05d6c48c1ce3d0ebf06aa38101b1e22"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
