name = "1.17.1 for friends"
author = "Small-Ku"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c19f2df3eeb81bc0a215b89aa7fe275cdadbb6496c406f6c80d339863c24a651"

[versions]
fabric = "0.13.3"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
