name = "1.17.1 for friends"
author = "Small-Ku"
version = "0.1.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6802c55c59b7324bc5b79d390696bca007401c76b9f08d7a371cacf0ef48129d"

[versions]
fabric = "0.13.3"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
