name = "1.17.1 for friends"
author = "Small-Ku"
version = "1.1.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "180d924f6cbd4421ac4e964c3675499048647081c59dba605417f0cffaff8677"

[versions]
fabric = "0.13.3"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
